# This is a deployment.yaml file. This is created by group (Aditya Indoori (G01129724), Prashant Sahu (G01149803), Gaurav Bahl (G01057667), Pushkal Reddy (G01166539), Deep Kumar (G01215145))
# This file is used for deploying the application on Kubernetes using Amazon EKS by picking the docker image of application from the Docker-hub repository.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: swe645p2-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: swe645p2
  template:
    metadata:
      labels:
        app: swe645p2
    spec:
      containers:
      - name: swe645p2
        image: psahu2/swe645repo:v1
        ports:
        - containerPort: 80
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: swe645p2-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: swe645p2
  type: LoadBalancer
